# Generated by Django 5.0.6 on 2024-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurnApp', '0002_product_image_product_is_featured_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
